### ISSUE TITLE
Tarea 4 - Error al instalar librosa

### ISSUE THREAD

**Issue by XXiaoR** [IIC2613-Inteligencia-Artificial-2022-1/Syllabus#116]
Hola! 

Al instalar librosa me aparece el siguiente error, alguna forma de corregirlo?

De antemano muchas gracias!

Collecting librosa
  Using cached librosa-0.9.2-py3-none-any.whl (214 kB)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages (from librosa) (1.0.2)
Collecting pooch>=1.0
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\http\client.py", line 461, in read
    n = self.readinto(b)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\http\client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Requirement already satisfied: scipy>=1.2.0 in c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages (from librosa) (1.7.3)
Requirement already satisfied: packaging>=20.0 in c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages (from librosa) (20.9)
Collecting numba>=0.45.1
  Downloading numba-0.55.2-cp37-cp37m-win_amd64.whl (2.4 MB)
     -------------------------------          1.8/2.4 MB 18.5 kB/s eta 0:00:28
    status = run_func(*args)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 342, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 220, in _make_candidate_from_link
    version=version,
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    version=version,
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 479, in _prepare_linked_requirement
    hashes,
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 159, in unpack_url
    hashes=hashes,
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\network\download.py", line 146, in __call__
    for chunk in chunks:
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\network\utils.py", line 87, in response_chunks
    decode_content=False,
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\100bu\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by SarahEverke** [comment]
Hola!
Si tienes problemas instalando la librería `librosa` te recomiendo utilizar Google Colab ya que en esa plataforma no debieses tener problema instalandola.
